### ISSUE TITLE
Release on F-Droid?

### ISSUE THREAD

**Issue by JonnyHaystack** [jtsalva/cloudmare#13]
Hi there, seeing as this app is open-source why not release it on F-Droid as well? Currently the only way to download it is on the play store which is not ideal.

**Comment by jtsalva** [comment]
Hi @JonnyHaystack, completely new to F-Droid, read a bit about it just now and see no reason why CloudMare can't be available through it. Do you have any experience with getting an app distributed on F-Droid which you could lend?

**Comment by JonnyHaystack** [comment]
I don't personally maintain any Android apps, so I'm afraid I haven't done it myself

**Comment by jtsalva** [comment]
@JonnyHaystack work in progress, opened a merge request 
 in `fdroid/fdroiddata` https://gitlab.com/fdroid/fdroiddata/-/merge_requests/6530

**Comment by jtsalva** [comment]
Successfully added CloudMare to F-Droid, see [commit](https://gitlab.com/fdroid/fdroiddata/-/commit/b69d0df7457f1296bb3f3d7bbdc23b6d4e8a4a37)

**Comment by resynth1943** [comment]
Shouldn't the F-Droid item also warn the user that this app connects to spyware web endpoints?

You can set that up in F-Droid. Look under "nonfree endpoints".

**Comment by jtsalva** [comment]
@resynth1943 please could you specify which endpoints you believe are 'spyware endpoints'?

**Comment by resynth1943** [comment]
@jtsalva [Cloudflare API endpoints.](https://codeberg.org/crimeflare/cloudflare-tor)

**Comment by resynth1943** [comment]
- [The application stores the location of the spyware web endpoint (Cloudflare API) here](https://github.com/jtsalva/cloudmare/blob/cb5e0b88c694530298a785dd8137842ecd14019f/app/src/main/java/dev/jtsalva/cloudmare/api/APIUtil.kt#L12)
- [The application generates and executes a HTTP request to the spyware web endpoint (Cloudflare API) here](https://github.com/jtsalva/cloudmare/blob/cb5e0b88c694530298a785dd8137842ecd14019f/app/src/main/java/dev/jtsalva/cloudmare/api/Request.kt#L92)

As such, you are expected to notify users by using the following "antifeature" notifications:

- [NonFreeNet](https://f-droid.org/wiki/page/Antifeature:NonFreeNet)

[More information on "antifeature" notifications can be seen here.](https://f-droid.org/en/docs/Anti-Features/)

**Comment by JonnyHaystack** [comment]
Really dude? This kind of thing is what gives the free software community a bad name. This is an app for cloudflare.. Of course it connects to cloudflare, and it's pretty rude to claim this app "connects to spyware web endpoints". Of course yes it should be labelled on F-Droid as connecting to nonfree web services, but anyone who wants to use this app is installing it to use with cloudflare. Don't act like there's some kind of subterfuge here.

**Comment by resynth1943** [comment]
I am not "acting like" anything. Please do not make egregious accusations.

As clearly seen in my above comment, this app connects to nonfree web endpoints.
You have admitted this:

> Of course yes it should be labelled on F-Droid as connecting to nonfree web services

I don't know what's up for debate here. I'm simply relaying the information provided by the F-Droid team, which is: applications that connect to nonfree web endpoints should be labelled as such.

**Comment by jtsalva** [comment]
@resynth1943 Whilst I don't agree with classifying Cloudflare's API as _spyware_, thanks for making me aware of [the F-Droid antifeature page](https://f-droid.org/en/docs/Anti-Features/). I will add the _missing_ label(s) when I get the chance. If you need this done urgently, please don't hold back from raising a PR yourself on F-Droid's repo :)

**Comment by resynth1943** [comment]
Thank you for being reasonable!

**Comment by JonnyHaystack** [comment]
> I am not "acting like" anything. Please do not make egregious accusations.

I don't know why it's hard to understand that going to someone and saying "your app uses spyware endpoints" is pretty ungracious. You said:
> Shouldn't the F-Droid item also **warn** the user that this app connects to spyware web endpoints?

The user does not need any "warning". If they are downloading a cloudflare app they are well aware of what cloudflare is. That is why I say you are acting like there is subterfuge, in that you claim this is an undisclosed behaviour and use emotive language ("spyware") as if this app is doing something malicious and unexpected to its users. While it's good practice to follow the guidelines, this is really nothing but a nitpick and not at all the big deal you make it out to be.

> As clearly seen in my above comment, this app connects to nonfree web endpoints.
> You have admitted this:

Yes.. nonfree does not always mean spyware.. That's ridiculous Stallmanist extremism. While I strongly believe in free software that does not mean you should attack anything that is not free. Maybe try to be less polarising.

> I don't know what's up for debate here. I'm simply relaying the information provided by the F-Droid team, which is: applications that connect to nonfree web endpoints should be labelled as such.

That is correct, there is nothing for debate. All I wished to say is that you could do with choosing your words a lot more wisely instead of using emotive language just because you hate proprietary software. I believe software should be free (libre) and users should be able to see what the programs they use are doing, but extremism like this is really not a good look for us all.

Anyways sorry @jtsalva for the noise and I hope you both have a nice day/night :smile:
