### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [jtsalva/cloudmare#19]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by jtsalva** [comment]
I've only just seen this now, adding screenshots is a good idea. I will _eventually_ get round to doing it. Feel free to raise a PR if you want too :)
